# Generated by Django 6.0.3 on 2026-05-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='treinoexercicio',
            name='rest_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='treinoexercicio',
            name='series',
            field=models.IntegerField(default=1),
        ),
    ]
